-- Run once against a tested database backup. This migration preserves all business IDs.
CREATE TABLE schema_migrations (version VARCHAR(100) PRIMARY KEY, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE companies (company_id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE branches (branch_id BIGINT AUTO_INCREMENT PRIMARY KEY, company_id BIGINT NOT NULL, name VARCHAR(150) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, FOREIGN KEY (company_id) REFERENCES companies(company_id));
CREATE TABLE departments (department_id BIGINT AUTO_INCREMENT PRIMARY KEY, company_id BIGINT NOT NULL, branch_id BIGINT NULL, name VARCHAR(150) NOT NULL, FOREIGN KEY (company_id) REFERENCES companies(company_id), FOREIGN KEY (branch_id) REFERENCES branches(branch_id));
CREATE TABLE sites (site_id BIGINT AUTO_INCREMENT PRIMARY KEY, branch_id BIGINT NOT NULL, name VARCHAR(150) NOT NULL, FOREIGN KEY (branch_id) REFERENCES branches(branch_id));

CREATE TABLE roles (role_id BIGINT AUTO_INCREMENT PRIMARY KEY, role_key VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, hierarchy_rank INT NOT NULL, is_system TINYINT(1) NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_role_rank (hierarchy_rank));
CREATE TABLE role_inheritance (role_id BIGINT NOT NULL, inherited_role_id BIGINT NOT NULL, PRIMARY KEY(role_id, inherited_role_id), FOREIGN KEY(role_id) REFERENCES roles(role_id), FOREIGN KEY(inherited_role_id) REFERENCES roles(role_id));
CREATE TABLE modules (module_id BIGINT AUTO_INCREMENT PRIMARY KEY, module_key VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, parent_module_id BIGINT NULL, sort_order INT NOT NULL DEFAULT 0, is_active TINYINT(1) NOT NULL DEFAULT 1, FOREIGN KEY(parent_module_id) REFERENCES modules(module_id));
CREATE TABLE permission_groups (permission_group_id BIGINT AUTO_INCREMENT PRIMARY KEY, module_id BIGINT NOT NULL, group_key VARCHAR(100) NOT NULL, name VARCHAR(120) NOT NULL, UNIQUE KEY uq_group(module_id, group_key), FOREIGN KEY(module_id) REFERENCES modules(module_id));
CREATE TABLE permissions (permission_id BIGINT AUTO_INCREMENT PRIMARY KEY, module_id BIGINT NOT NULL, permission_group_id BIGINT NULL, permission_key VARCHAR(160) NOT NULL UNIQUE, action_key VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, FOREIGN KEY(module_id) REFERENCES modules(module_id), FOREIGN KEY(permission_group_id) REFERENCES permission_groups(permission_group_id));
CREATE TABLE role_permissions (role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, effect ENUM('allow','deny') NOT NULL DEFAULT 'allow', PRIMARY KEY(role_id, permission_id), FOREIGN KEY(role_id) REFERENCES roles(role_id), FOREIGN KEY(permission_id) REFERENCES permissions(permission_id));
CREATE TABLE user_permissions (user_id INT NOT NULL, permission_id BIGINT NOT NULL, effect ENUM('allow','deny') NOT NULL, PRIMARY KEY(user_id, permission_id), FOREIGN KEY(user_id) REFERENCES users(user_id), FOREIGN KEY(permission_id) REFERENCES permissions(permission_id));

ALTER TABLE users ADD COLUMN role_ref_id BIGINT NULL, ADD COLUMN company_id BIGINT NULL, ADD COLUMN branch_id BIGINT NULL, ADD COLUMN department_id BIGINT NULL, ADD COLUMN manager_user_id INT NULL, ADD COLUMN password_changed_at DATETIME NULL, ADD COLUMN force_password_change TINYINT(1) NOT NULL DEFAULT 0, ADD COLUMN deleted_at DATETIME NULL, ADD COLUMN permission_version INT NOT NULL DEFAULT 1;
ALTER TABLE users MODIFY username VARCHAR(100) NOT NULL, MODIFY password_hash VARCHAR(255) NOT NULL, MODIFY status ENUM('active','inactive','blocked','locked','deleted','password_expired','force_password_reset') NOT NULL DEFAULT 'active', ADD UNIQUE KEY uq_users_username(username), ADD KEY idx_users_role_status(role_ref_id,status);
ALTER TABLE users ADD CONSTRAINT fk_users_role FOREIGN KEY(role_ref_id) REFERENCES roles(role_id), ADD CONSTRAINT fk_users_company FOREIGN KEY(company_id) REFERENCES companies(company_id), ADD CONSTRAINT fk_users_branch FOREIGN KEY(branch_id) REFERENCES branches(branch_id), ADD CONSTRAINT fk_users_department FOREIGN KEY(department_id) REFERENCES departments(department_id), ADD CONSTRAINT fk_users_manager FOREIGN KEY(manager_user_id) REFERENCES users(user_id);
CREATE TABLE user_project_assignments (user_id INT NOT NULL, project_id INT NOT NULL, PRIMARY KEY(user_id,project_id), FOREIGN KEY(user_id) REFERENCES users(user_id), FOREIGN KEY(project_id) REFERENCES projects(project_id));
CREATE TABLE user_memberships (user_id INT NOT NULL, company_id BIGINT NOT NULL, branch_id BIGINT NULL, department_id BIGINT NULL, PRIMARY KEY(user_id,company_id,branch_id,department_id), FOREIGN KEY(user_id) REFERENCES users(user_id), FOREIGN KEY(company_id) REFERENCES companies(company_id));

ALTER TABLE projects ADD COLUMN company_id BIGINT NULL, ADD COLUMN branch_id BIGINT NULL, ADD COLUMN department_id BIGINT NULL, ADD COLUMN site_id BIGINT NULL, ADD COLUMN owner_user_id INT NULL;
ALTER TABLE vendors ADD COLUMN company_id BIGINT NULL, ADD COLUMN branch_id BIGINT NULL, ADD COLUMN owner_user_id INT NULL;
ALTER TABLE purchase_request ADD COLUMN created_by_user_id INT NULL;
ALTER TABLE purchase_orders ADD COLUMN created_by_user_id INT NULL;

CREATE TABLE data_scope_policies (policy_id BIGINT AUTO_INCREMENT PRIMARY KEY, subject_type ENUM('role','user') NOT NULL, subject_id BIGINT NOT NULL, module_key VARCHAR(100) NOT NULL, scope ENUM('own','department','project','company','branch','site','all') NOT NULL, UNIQUE KEY uq_scope(subject_type,subject_id,module_key));
CREATE TABLE field_policies (policy_id BIGINT AUTO_INCREMENT PRIMARY KEY, subject_type ENUM('role','user') NOT NULL, subject_id BIGINT NOT NULL, module_key VARCHAR(100) NOT NULL, field_key VARCHAR(100) NOT NULL, access_level ENUM('hidden','readonly','editable') NOT NULL, UNIQUE KEY uq_field_policy(subject_type,subject_id,module_key,field_key));

CREATE TABLE sessions (session_id CHAR(36) PRIMARY KEY, user_id INT NOT NULL, token_family_id CHAR(36) NOT NULL, ip_address VARCHAR(64) NULL, user_agent VARCHAR(512) NULL, device_name VARCHAR(160) NULL, browser VARCHAR(120) NULL, os VARCHAR(120) NULL, login_at DATETIME NOT NULL, last_activity_at DATETIME NOT NULL, expires_at DATETIME NOT NULL, terminated_at DATETIME NULL, termination_reason VARCHAR(100) NULL, KEY idx_session_user_active(user_id,terminated_at,expires_at), FOREIGN KEY(user_id) REFERENCES users(user_id));
ALTER TABLE refresh_tokens ADD COLUMN session_id CHAR(36) NULL, ADD COLUMN token_family_id CHAR(36) NULL, ADD COLUMN replaced_by_jti VARCHAR(64) NULL, ADD COLUMN last_used_at DATETIME NULL, ADD KEY idx_refresh_session(session_id), ADD CONSTRAINT fk_refresh_session FOREIGN KEY(session_id) REFERENCES sessions(session_id);
CREATE TABLE login_attempts (attempt_id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(100) NOT NULL, user_id INT NULL, ip_address VARCHAR(64) NULL, user_agent VARCHAR(512) NULL, was_successful TINYINT(1) NOT NULL, attempted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_login_lock(username,ip_address,attempted_at));
CREATE TABLE password_history (history_id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, password_hash VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_password_history(user_id,created_at), FOREIGN KEY(user_id) REFERENCES users(user_id));
CREATE TABLE security_events (event_id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, event_type VARCHAR(100) NOT NULL, severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'low', ip_address VARCHAR(64) NULL, user_agent VARCHAR(512) NULL, details JSON NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, KEY idx_security_user_created(user_id,created_at));
CREATE TABLE audit_logs (audit_id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, action VARCHAR(100) NOT NULL, module_key VARCHAR(100) NULL, entity_type VARCHAR(100) NULL, entity_id VARCHAR(100) NULL, ip_address VARCHAR(64) NULL, user_agent VARCHAR(512) NULL, old_value JSON NULL, new_value JSON NULL, request_id CHAR(36) NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, KEY idx_audit_module_created(module_key,created_at), KEY idx_audit_user_created(user_id,created_at));

INSERT INTO companies(name) VALUES ('Default Company');
INSERT INTO branches(company_id,name) SELECT company_id,'Default Branch' FROM companies WHERE name='Default Company';
INSERT INTO roles(role_key,name,hierarchy_rank,is_system) VALUES ('super_admin','Super Admin',500,1),('admin','Admin',400,1),('manager','Manager',300,1),('user','User',200,1),('viewer','Viewer',100,1);
INSERT INTO modules(module_key,name,sort_order) VALUES ('dashboard','Dashboard',10),('project','Projects',20),('vendor','Vendors',30),('purchase_request','Purchase Requests',40),('purchase_order','Purchase Orders',50),('report','Reports',60),('user','Users',70),('role','Roles',80),('settings','Settings',90),('session','Sessions',100),('audit_log','Audit Logs',110);
INSERT INTO permissions(module_id,permission_key,action_key,name) SELECT module_id, CONCAT(module_key,'.',action_key), action_key, CONCAT(name,' ',action_key) FROM modules JOIN (SELECT 'view' action_key UNION SELECT 'create' UNION SELECT 'edit' UNION SELECT 'delete' UNION SELECT 'approve' UNION SELECT 'reject' UNION SELECT 'export' UNION SELECT 'import' UNION SELECT 'print' UNION SELECT 'download' UNION SELECT 'manage') actions;
UPDATE users SET company_id=(SELECT company_id FROM companies WHERE name='Default Company'), branch_id=(SELECT branch_id FROM branches WHERE name='Default Branch');
UPDATE users u JOIN roles r ON r.role_key=CASE WHEN u.role_id='Admin' THEN 'admin' WHEN u.role_id='Purchase Senior Executive' THEN 'manager' WHEN u.role_id IN ('Purchase Executive','3') THEN 'user' WHEN u.role_id IN ('Site Supervisor','5') THEN 'viewer' ELSE 'viewer' END SET u.role_ref_id=r.role_id, u.status=COALESCE(NULLIF(u.status,''),'active');
UPDATE projects SET company_id=(SELECT company_id FROM companies WHERE name='Default Company'), branch_id=(SELECT branch_id FROM branches WHERE name='Default Branch');
UPDATE vendors SET company_id=(SELECT company_id FROM companies WHERE name='Default Company'), branch_id=(SELECT branch_id FROM branches WHERE name='Default Branch');
INSERT INTO role_permissions(role_id,permission_id,effect) SELECT r.role_id,p.permission_id,'allow' FROM roles r JOIN permissions p WHERE r.role_key='super_admin';
INSERT INTO role_permissions(role_id,permission_id,effect) SELECT r.role_id,p.permission_id,'allow' FROM roles r JOIN permissions p WHERE r.role_key='admin';
INSERT INTO role_permissions(role_id,permission_id,effect) SELECT r.role_id,p.permission_id,'allow' FROM roles r JOIN permissions p WHERE r.role_key='manager' AND p.permission_key IN ('dashboard.view','project.view','vendor.view','purchase_request.view','purchase_request.create','purchase_request.approve','purchase_order.view','purchase_order.create','report.view','session.view');
INSERT INTO role_permissions(role_id,permission_id,effect) SELECT r.role_id,p.permission_id,'allow' FROM roles r JOIN permissions p WHERE r.role_key='user' AND p.permission_key IN ('dashboard.view','project.view','vendor.view','purchase_request.view','purchase_request.create','purchase_order.view');
INSERT INTO role_permissions(role_id,permission_id,effect) SELECT r.role_id,p.permission_id,'allow' FROM roles r JOIN permissions p WHERE r.role_key='viewer' AND p.action_key='view';
INSERT INTO audit_logs(action,module_key,new_value) VALUES ('AUTH_MIGRATION','settings',JSON_OBJECT('legacy_role_mapping','completed'));
INSERT INTO schema_migrations(version) VALUES ('001_enterprise_auth');
