const { z } = require('zod');
const authService = require('../services/authService'); const refreshService=require('../services/refreshService'); const logoutService=require('../services/logoutService');
const { cookieOptions }=require('../utils/security'); const { snapshot }=require('../services/permissionService'); const { audit }=require('../services/auditService');
const ACCESS=process.env.ACCESS_COOKIE_NAME||'pm_access', REFRESH=process.env.REFRESH_COOKIE_NAME||'pm_refresh';
const loginSchema=z.object({username:z.string().trim().min(3).max(100),password:z.string().min(1).max(256)});
const setCookies=(res,access,refresh)=>{res.cookie(ACCESS,access,cookieOptions(15*60*1000));res.cookie(REFRESH,refresh,cookieOptions(7*24*60*60*1000));}; const clear=(res)=>{res.clearCookie(ACCESS,cookieOptions());res.clearCookie(REFRESH,cookieOptions());};
const login=async(req,res,next)=>{try{const {username,password}=loginSchema.parse(req.body);const result=await authService.login(username,password,req);setCookies(res,result.accessToken,result.refreshToken); await audit({...req,user:{user_id:result.user.id}},'LOGIN',{moduleKey:'session',entityId:result.sessionId});res.json({user:result.user,sessionId:result.sessionId});}catch(error){if(error.name==='ZodError')error={status:400,code:'VALIDATION_ERROR',message:'Invalid login request'};next(error);}};
const refresh=async(req,res,next)=>{try{const result=await refreshService.refresh(req.cookies?.[REFRESH]);setCookies(res,result.accessToken,result.refreshToken);res.status(204).end();}catch(error){clear(res);next(error);}};
const logout=async(req,res,next)=>{try{await logoutService.logout(req.cookies?.[REFRESH]);clear(res);res.status(204).end();}catch(error){next(error);}};
const logoutAll=async(req,res,next)=>{try{await logoutService.logout(null,true,req.user.user_id);clear(res);await audit(req,'LOGOUT_ALL',{moduleKey:'session'});res.status(204).end();}catch(error){next(error);}};
const me=async(req,res,next)=>{try{res.json({user:authService.safeUser(req.user),authorization:await snapshot(req.user.user_id)});}catch(error){next(error);}};
module.exports={login,refresh,logout,logoutAll,me};
